import { Inter } from "next/font/google";
import "./globals.css";
import { SearchContextProvider } from "./context/searchContext";
import Loader from "./Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Rent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SearchContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <Loader>{children}</Loader>
        </body>
      </html>
    </SearchContextProvider>
  );
}
